project:
  type: website
  output-dir: docs

website:
  title: "Git Training - INN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: prep.qmd
        text: Preparation
      - href: schedule.qmd
        text: Schedule
      - href: resources.qmd
        text: Resources
      - href: 100days.qmd
        text: 100 Days of Version Control

format:
  html:
    theme:
      light: simplex
      dark: cyborg
    css: styles.css
    toc: true